name: kantan.xpath
markdown: redcarpet
highlighter: rouge
baseurl: /kantan.xpath

kramdown:
  input: GFM

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

collections:
  tut:
    output: true
