name: kantan.xpath
markdown: kramdown
highlighter: pygments
baseurl: /kantan.xpath

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

collections:
  tut:
    output: true
